import yaml
import json
from pathlib import Path
from datetime import datetime
from rich.console import Console

console = Console()

class NotesManager:
    """Synthesizes raw data into structured Markdown notes (ADHD Optimized)."""

    def __init__(self, orchestrator):
        self.tio = orchestrator
        self.root = Path("/srv/test.io")
        self.output_dir = self.root / "academy/notes"
        self.tmp_dir = self.root / "academy/tmp"

    def run(self, topic):
        if not topic:
            self.tio.log("Error: Topic required for Notes (e.g., 'tio n academy')", "red")
            return

        # Handle '*' for batch processing
        if topic == "*":
            self.tio.log("Batch processing all available academy tmp data...")
            yml_files = self.tmp_dir.glob("*.yml")
            for yml_file in yml_files:
                self.process_topic(yml_file.stem)
            return

        self.process_topic(topic)

    def process_topic(self, topic):
        source_file = self.tmp_dir / f"{topic}.yml"
        if not source_file.exists():
            self.tio.log(f"Error: Source data for '{topic}' not found at {source_file}", "red")
            return

        with open(source_file, 'r') as f:
            try:
                data = yaml.safe_load(f)
            except Exception as e:
                self.tio.log(f"Error parsing YAML for {topic}: {e}", "red")
                return

        if not data:
            self.tio.log(f"Warning: {topic}.yml is empty.", "yellow")
            return

        title = data.get('title', topic.replace('_', ' ').capitalize())
        self.tio.log(f"Synthesizing notes for: [bold]{title}[/bold]")

        md_content = f"# {title} Reference Notes\n\n"
        md_content += f"**Last Updated:** {datetime.now().strftime('%Y-%m-%d')}\n\n"
        
        for key, value in data.items():
            if key in ['title', 'author', 'updated']: continue
            
            md_content += f"## {key.replace('_', ' ').capitalize()}\n"
            if isinstance(value, dict):
                for sub_key, sub_val in value.items():
                    md_content += f"### {sub_key.replace('_', ' ').capitalize()}\n"
                    if isinstance(sub_val, list):
                        for item in sub_val: md_content += f"* {item}\n"
                    elif isinstance(sub_val, dict):
                         for k, v in sub_val.items(): md_content += f"* **{k}:** {v}\n"
                    else:
                        md_content += f"{sub_val}\n"
                    md_content += "\n"
            elif isinstance(value, list):
                for item in value: md_content += f"* {item}\n"
            else:
                md_content += f"{value}\n"
            md_content += "\n"

        md_content += "---\n*Generated by Tio-CLI Notes Processor*"

        self.output_dir.mkdir(parents=True, exist_ok=True)
        md_path = self.output_dir / f"notes_{topic}.md"
        with open(md_path, 'w') as f:
            f.write(md_content)

        self.tio.log(f"  [✔] Generated: {md_path.name}", style="green")
